from rest_framework import serializers
from .models import DistributionMetrics, CreditHistory, DistributedCreditHistory

class DistributionMetricsSerializer(serializers.Serializer):
    id = serializers.CharField(source='id', read_only=True)
    mfi_id = serializers.UUIDField()
    date = serializers.DateTimeField(read_only=True)
    total_loans = serializers.IntegerField()
    total_amount = serializers.DecimalField(max_digits=15, decimal_places=2)
    average_loan_size = serializers.DecimalField(max_digits=15, decimal_places=2)
    location_distribution = serializers.DictField()
    active_borrowers_by_location = serializers.DictField()
    loan_repayment_rate_by_location = serializers.DictField()
    average_loan_size_by_location = serializers.DictField()

class CreditHistorySerializer(serializers.Serializer):
    id = serializers.CharField(source='id', read_only=True)
    borrower_id = serializers.UUIDField()
    mfi_id = serializers.UUIDField()
    mfi_location = serializers.CharField()
    date = serializers.DateTimeField(read_only=True)
    credit_score = serializers.IntegerField()
    payment_history = serializers.DictField()
    loan_utilization = serializers.DecimalField(max_digits=5, decimal_places=2)
    loan_diversity = serializers.IntegerField()
    total_loans = serializers.IntegerField()
    total_amount_borrowed = serializers.DecimalField(max_digits=15, decimal_places=2)
    total_amount_repaid = serializers.DecimalField(max_digits=15, decimal_places=2)
    on_time_payments = serializers.IntegerField()
    late_payments = serializers.IntegerField()
    defaulted_payments = serializers.IntegerField()
    risk_factors = serializers.ListField(child=serializers.CharField())

class DistributedCreditHistorySerializer(serializers.Serializer):
    id = serializers.CharField(source='id', read_only=True)
    borrower_id = serializers.UUIDField()
    national_id = serializers.CharField()
    location = serializers.CharField()
    date = serializers.DateTimeField(read_only=True)
    aggregated_credit_score = serializers.IntegerField()
    contributing_mfis = serializers.ListField(child=serializers.DictField())
    total_loans_count = serializers.IntegerField()
    total_amount_borrowed = serializers.DecimalField(max_digits=15, decimal_places=2)
    total_amount_repaid = serializers.DecimalField(max_digits=15, decimal_places=2)
    on_time_payments = serializers.IntegerField()
    late_payments = serializers.IntegerField()
    defaulted_payments = serializers.IntegerField()
    risk_factors = serializers.ListField(child=serializers.CharField())
    mfi_records = serializers.DictField()
    data_sharing_log = serializers.ListField(child=serializers.DictField())
