# Generated by Django 5.1.7 on 2025-03-26 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('founding_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_loans_disbursed', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('num_active_borrowers', models.IntegerField(default=0)),
                ('regulatory_status', models.CharField(choices=[('REGISTERED', 'Registered'), ('PENDING', 'Pending Approval'), ('SUSPENDED', 'Suspended')], default='REGISTERED', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Microfinance Institution',
                'verbose_name_plural': 'Microfinance Institutions',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('BORROWER', 'Borrower'), ('LOAN_OFFICER', 'Loan Officer'), ('MFI_ADMIN', 'MFI Admin'), ('CREDIT_ANALYST', 'Credit Analyst'), ('AUDITOR', 'Auditor'), ('SYSTEM_ADMIN', 'System Admin')], default='BORROWER', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.mfi'),
        ),
    ]
