# Generated by Django 5.1.7 on 2025-04-15 21:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_mfi_alter_user_groups_alter_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfi',
            name='id',
        ),
        migrations.AddField(
            model_name='mfi',
            name='location',
            field=models.CharField(default='Maseruka', max_length=255),
        ),
        migrations.AddField(
            model_name='mfi',
            name='mfi_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to for permission grouping', related_name='letsema_user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LOAN_OFFICER', 'Loan Officer'), ('MFI_ADMIN', 'MFI Admin'), ('CREDIT_ANALYST', 'Credit Analyst'), ('SYSTEM_ADMIN', 'System Admin')], default='BORROWER', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user', related_name='letsema_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('borrower_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.JSONField()),
                ('password_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(null=True)),
                ('mfi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.mfi')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REPAID', 'Repaid')], default='PENDING', max_length=20)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('term', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('interest', models.DecimalField(decimal_places=3, max_digits=15)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.borrower')),
                ('mfi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.mfi')),
            ],
        ),
    ]
