# Generated by Django 5.1.7 on 2025-04-15 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_mfi_id_mfi_location_mfi_mfi_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='borrower',
            name='date_of_birth',
            field=models.DateField(default='1990-01-01'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
