# Generated by Django 5.1.7 on 2025-04-20 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_borrower_password_hash_borrower_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='mfi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.mfi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LOAN_OFFICER', 'Loan Officer'), ('MFI_ADMIN', 'MFI Admin'), ('CREDIT_ANALYST', 'Credit Analyst'), ('SYSTEM_ADMIN', 'System Admin'), ('BORROWER', 'borrower')], default='BORROWER', max_length=20),
        ),
    ]
