# Generated by Django 5.1.7 on 2025-04-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_borrower_mfi_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
