# Generated by Django 5.1.7 on 2025-04-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.mfi'),
        ),
    ]
