# Generated by Django 5.1.7 on 2025-04-27 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_mfi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfi',
            field=models.ForeignKey(blank=True, db_column='mfi_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.mfi'),
        ),
    ]
