version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${SUPABASE_DBNAME}
      - POSTGRES_USER=${SUPABASE_USER}
      - POSTGRES_PASSWORD=${SUPABASE_PASSWORD}
    ports:
      - "5433:5432"

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${SUPABASE_USER}:${SUPABASE_PASSWORD}@db:5432/${SUPABASE_DBNAME}
      - DJANGO_SETTINGS_MODULE=backend.settings
    depends_on:
      - db
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/users
    depends_on:
      - backend

volumes:
  postgres_data:
