# Generated by Django 5.1.7 on 2025-04-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='purpose',
            field=models.CharField(blank=True, choices=[('PERSONAL', 'Personal'), ('BUSINESS', 'Business'), ('EDUCATION', 'Education'), ('MEDICAL', 'Medical'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
