# Generated by Django 5.1.7 on 2025-04-24 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='term',
            field=models.IntegerField(choices=[(3, '3 months'), (6, '6 months'), (12, '12 months'), (24, '24 months'), (36, '36 months'), (48, '48 months'), (60, '60 months')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
