# Generated by Django 5.1.7 on 2025-04-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_repayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Cheque')], max_length=20, null=True),
        ),
    ]
