# Generated by Django 5.1.7 on 2025-04-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_repayment_payment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('UPCOMING', 'Upcoming'), ('VERIFIED', 'Verified')], default='PENDING', max_length=20),
        ),
    ]
